### ISSUE TITLE
Why is the version number change for release?

### ISSUE THREAD

**Issue by xied75** [gsvm/loongson-dotnet#4]
aspnetcore-runtime-3.1.7-ea-20200819-linux-loongson3a.tar.gz
dotnet-runtime-3.1.7-ea-20200819-linux-loongson3a.tar.gz
dotnet-sdk-3.1.107-ea-20200819-linux-loongson3a.tar.gz

Are those 3.1.7 tied to upstream 3.1.7 now?  I thought our anchor is 3.0.1 until the porting is done for the first round of work?

Best regards,

Dong

**Comment by theaoqi** [comment]
> Are those 3.1.7 tied to upstream 3.1.7 now?

Yes. 3.1.7 is the upstream version, while ea-2020XXXX is the Loongson version identifier for EA builds.

> I thought our anchor is 3.0.1 until the porting is done for the first round of work?

No. The GA version of Loongson will be the latest upstream version which is under maintenance. [.NET Core 3.0](https://dotnet.microsoft.com/download/dotnet-core) has reached end of life, so I think .NET Core 3.1 may be a better choice and it is [recommended](https://dotnet.microsoft.com/download/dotnet-core). 3.1.0 will not be our GA version, the latest 3.1 will be.

In addition, it's hard to say when "the porting is done". On one hand, a GA version may be the time; on the other hand, we will continue the porting job for a lone time, and the job includes improving performance, improving stability under stress, improving productization and **keeping up with the latest upstream version**.

**Comment by xiangzhai** [comment]
Hi @xied75 

Version | Status | Latest release | Latest release date | End of support
-- | -- | -- | -- | --
.NET Core 3.1 (recommended) | LTS | 3.1.7 | 2020-08-11 | 2022-12-03

Welcome feedback if 3.1 compatibility issue.

Thanks,
Leslie Zhai

**Comment by xied75** [comment]
Thanks @theaoqi & @xiangzhai , all understood.

My point is that it is much harder to aim for a moving target. Given we still have lots of TODO to finish, I was thinking the best strategy would be to just fix on one commit to at least get all tests pass before we move the anchor again. Otherwise the diff between the two anchors would bring extra workload to the team while we should focus on the TODOs. Suppose there are big changes then lots of work would be cancelled ( you could argue that eventually these work need to be done anyway, which I agree).

If 3.1.7 is LTS then I suggest to anchor on this for now, (i.e. the commit/tag e8b1784, not the branch 3.1.7, otherwise you need to merge in upstream tails periodically without much benefit).

BTW, I believe our work on the v3.x will never make it back to the upstream according to what I read before. So I guess the MIPS port 3.x will live here, once we have a stable release of v3.x, then we can start to pick the tails of upstream branch 3.1.7 and get the v3.x into maintenance mode.

**Comment by theaoqi** [comment]
Our strategy for synchronizing code with upstream would be synchronizing per release/[tag](https://github.com/dotnet/coreclr/tags) (or every few releases), i.e. v3.1.X. We will not synchronize per commit, which would be a disaster for us for now. We will not stay at an old version for a long time, since we hope our users could use the latest upstream version which contains the latest bug fixes and security fixes. I believe Microsoft will fully test their release tags, so I trust them and use them as soon as possible. Besides, our test strategy, for now, is to find the differences between MIPS and other architectures. We don't need to care about the differences between two commits (or anchors) very much.

> If 3.1.7 is LTS then I suggest to anchor on this for now, (i.e. the commit/tag e8b1784, not the branch 3.1.7, otherwise you need to merge in upstream tails periodically without much benefit).

I think 3.1 is a LTS version, not 3.1.7. There is not a 3.1.7 branch. There is 3.1 branch, i.e. [release/3.1](https://github.com/dotnet/coreclr/tree/release/3.1)

> BTW, I believe our work on the v3.x will never make it back to the upstream according to what I read before. 

Yes.

> So I guess the MIPS port 3.x will live here, 

You are right.

> once we have a stable release of v3.x, then we can start to pick the tails of upstream branch 3.1.7 and get the v3.x into maintenance mode.

We already begin this:) When v3.1.8/v3.1.9... is released, we will try to merge them.
